### ISSUE TITLE
Solver isn't working on model.energy?

### ISSUE THREAD

**Issue by christopherstelter** [PyPSA/whobs-server#21]
Existing solved solutions seem to still work, but when I try a new solution, I get errors in javascript console, and it never finishes:

```
7697270f-d054-4192-acd5-94436d21eb7d:1     Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
model.energy/:1 Uncaught SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at poll.onload (solver-230817.js:439:17)
7697270f-d054-4192-acd5-94436d21eb7d:1     Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
model.energy/:1 Uncaught SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at poll.onload (solver-230817.js:439:17)
7697270f-d054-4192-acd5-94436d21eb7d:1     Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
model.energy/:1 Uncaught SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at poll.onload (solver-230817.js:439:17)
7697270f-d054-4192-acd5-94436d21eb7d:1     Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
model.energy/:1 Uncaught SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at poll.onload (solver-230817.js:439:17)
7697270f-d054-4192-acd5-94436d21eb7d:1     Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
model.energy/:1 Uncaught SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at poll.onload (solver-230817.js:439:17)
7697270f-d054-4192-acd5-94436d21eb7d:1     Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
model.energy/:1 Uncaught SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at poll.onload (solver-230817.js:439:17)
```

**Comment by tranberg** [comment]
I can't reproduce this problem (for new solutions). What exactly is your input?

**Comment by nworbmot** [comment]
On the weekend I added a bugfix, that was particularly causing problems when hydrogen storage was turned off:
https://github.com/PyPSA/whobs-server/commit/3e00b6df8fedee73b9f278e65d904422a1f24cae
